SERVER: "production"
PORT: 22
BRANCH: "dev"
WORK_SERVER: "rabbitmq-server"
VENV_REQUIREMENTS: "requirements.txt"

USER: "sebuntu-1"
PASSWORD: "njkelfrjq"
HOST: "192.168.56.101"
PATH: "/home/sebuntu-1/work/fabtest/"
REPOSITORY: "https://github.com/faoxis/gittest.git"