---
title:
    "Основные сведения"
header:
    - "ОГРНИП"
    - "ИНН"
    - "Статус"
    - "Фамилия"
    - "Имя"
    - "Отчество"
body:
    - "@ОГРНИП"
    - "@ИННФЛ"
    - "STATE:СвПрекращ.СвСтатус.@НаимСтатус"
    - "СвФЛ.ФИОРус.@Фамилия"
    - "СвФЛ.ФИОРус.@Имя"
    - "СвФЛ.ФИОРус.@Отчество"
node:
    "СвФЛ"